### ISSUE TITLE
Top camera images are same for sevral sampling times (

### ISSUE THREAD

**Issue by RBhupi** [waggle-sensor/plugin-imagesampler#5]
I'm having this issue with my cloud motion vectors from long time. They all seem to have a similar magnitude of 2.842 (that's my rounding problem, but this means zero motion detected).
, even when there's motion present. I checked it offline by downloading images too and the same value showed up. In my old This happens when there's no motion, but what I don't understand is why it's happening so often when there are clouds present, and why it's sometimes really high even when there's no special moving features like birds or anything.

After a lot of digging, I found out that the camera isn't giving me a new image every time I take a sample. Instead, it's giving me the same image for several samples. At first, I thought it was my code that was causing this, but I realized that the image-sampler is doing the same thing. So I downloaded some images to check, and they had the same problem too.

So, I need some help to fix this. Can someone assist me in identifying the root cause of this issue? https://portal.sagecontinuum.org/query-browser?nodes=W021&start=2023-04-24T18%3A00%3A25.000Z&apps=registry.sagecontinuum.org%2Ftheone%2Fimagesampler%3A0.3.1

**Comment by gemblerz** [comment]
I know it's been sitting here for a long time. And, this repository is not even the right place to raise this issue. But to answer the question for future reference (you may have already resolved this), please open the PyWaggle's Camera class whenever you need to, and do not leave it open when not using. For example,

```python
from waggle.data.vision import Camera

with Camera() as camera:
    sample = camera.snapshot()

# process the sample here
```
You open the camera and capture a snapshot. Then, close the camera before processing. Next time you open it again which will give you a new image.

Do __NOT__ do the following,
```python
with Camera() as camera:
    while True:
        sample = camera.snapshot()
        # process the sample
```
The above code can cause the problem that you ran into because the processing can take time and the next `camera.snapshot()` will give you the buffered image instead of the new image.

**Comment by seanshahkarami** [comment]
On this topic, in retrospect, maybe it was a mistake for me to use a unified Camera object for both images and video?

Do you all think it would have been more clear to have distinct things for images vs video? For example:

```
# opens and new stream and captures images without buffering
img = waggle.capture_image("top-camera")

# this keeps the camera open
for img in waggle.capture_video("bottom-camera"):
    process image
```

Not saying we use this exact API but instead, that it makes it more clear that one is a "one shot" thing and there other requires continuous processing.
